debug: true
logging:
  #file:
    #name: app.log
  level:
    root: info
    org.apache.kafka: info
spring:
  main:
    web-application-type: none
  application:
    name: consent-processor
  cloud:
    stream:
      function:
        definition: processMdmData
      bindings:
        processMdmData-in-0:
          destination: mdmbridge
          consumer:
            use-native-decoding: true
      kafka:
        streams:
          binder:
            functions:
              processMdmData:
                application-id: ${spring.application.name}-processMdmData
            applicationId: ${spring.application.name}-stream
            brokers:
            - localhost:19093
            - localhost:19094
            configuration:
              schema.registry.url: http://localhost:8081              
              default.key.serde: io.confluent.kafka.streams.serdes.avro.PrimitiveAvroSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
              processing.guarantee: exactly_once
            autoCreateTopics: false
            autoAddPartitions: false
          bindings:
            processMdmData-in-0.consumer.keySerde: io.confluent.kafka.streams.serdes.avro.PrimitiveAvroSerde
            processMdmData-in-0.consumer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
