/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.corp.concepts.notification.models;
@org.apache.avro.specific.AvroGenerated
public enum ConsentType implements org.apache.avro.generic.GenericEnumSymbol<ConsentType> {
  Mesaj, Arama, Eposta  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ConsentType\",\"namespace\":\"com.corp.concepts.notification.models\",\"symbols\":[\"Mesaj\",\"Arama\",\"Eposta\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
