/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.corp.concepts.notification.models;
@org.apache.avro.specific.AvroGenerated
public enum RecipientType implements org.apache.avro.generic.GenericEnumSymbol<RecipientType> {
  Bireysel, Kurumsal  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RecipientType\",\"namespace\":\"com.corp.concepts.notification.models\",\"symbols\":[\"Bireysel\",\"Kurumsal\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
