debug: false
logging:
  #file:
    #name: app.log
  level:
    root: info
    org.apache.kafka: error
    org.springframework.kafka.config: debug
spring:
  datasource:
    url: jdbc:h2:mem:notification
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  cloud:
    stream:
      function:
        definition: output
      kafka:
        binder:
          autoCreateTopics: false
          autoAddPartitions: false
          brokers:
          - localhost:19093
          - localhost:19094
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.apache.kafka.common.serialization.StringSerializer          
      bindings:
        output-out-0:
          destination: consent
          producer:
            useNativeEncoding: true           
  application:
    name: consent-writer